name: FinalProje CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: 'write'

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 Corretto
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Coverage
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Fail PR if overall coverage is less than 50%
      if: ${{ steps.jacoco.outputs.coverage-overall < 50.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 50%!') 
