name: FinalProje CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 Corretto
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        title: Code Coverage
        update-comment: true




